# Generated by Django 5.0.7 on 2024-07-21 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Targa',
            fields=[
                ('targa', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('data_emissione', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Veicolo',
            fields=[
                ('numero_telaio', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('modello', models.CharField(max_length=100)),
                ('data_produzione', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Revisione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_revisione', models.CharField(max_length=17)),
                ('data_revisione', models.DateField()),
                ('stato', models.CharField(max_length=100)),
                ('motivazione', models.CharField(max_length=100, null=True)),
                ('targa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.targa')),
            ],
        ),
        migrations.CreateModel(
            name='TargaAttiva',
            fields=[
                ('targa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hello.targa')),
                ('numero_telaio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hello.veicolo')),
            ],
        ),
        migrations.CreateModel(
            name='TargaRestituita',
            fields=[
                ('targa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hello.targa')),
                ('data_restituzione', models.DateField()),
                ('numero_telaio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hello.veicolo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='revisione',
            constraint=models.UniqueConstraint(fields=('targa', 'numero_revisione'), name='unique_targa_numero_revisione'),
        ),
    ]
