# Generated by Django 5.0.6 on 2024-07-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisione',
            name='numero_revisione',
            field=models.IntegerField(),
        ),
    ]
