# Generated by Django 5.0.6 on 2024-08-05 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_revisione_numero_revisione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targarestituita',
            name='numero_telaio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.veicolo'),
        ),
    ]
