# Generated by Django 5.0.6 on 2024-08-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_targarestituita_numero_telaio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targaattiva',
            name='numero_telaio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hello.veicolo'),
        ),
        migrations.AlterField(
            model_name='targaattiva',
            name='targa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='hello.targa'),
        ),
        migrations.AlterField(
            model_name='targarestituita',
            name='numero_telaio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.veicolo'),
        ),
        migrations.AlterField(
            model_name='targarestituita',
            name='targa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='hello.targa'),
        ),
    ]
